export const THAI_NAKSHATRAS = [
  { id: 1, name: "อัศวินี", category: "ทลิทโท", symbol: "หัวม้า" },
  { id: 2, name: "ภรณี", category: "มหัทธโณ", symbol: "ฝาละมี" },
  { id: 3, name: "กฤติกา", category: "โจโร", symbol: "กงจักร/ขวาน" },
  { id: 4, name: "โรหิณี", category: "ภูมิปาโล", symbol: "รถฟาง/ล้อรถ" },
  { id: 5, name: "มฤคศิระ", category: "เทศาตรี", symbol: "หัวกวาง" },
  { id: 6, name: "อารทรา", category: "เทวี", symbol: "หยาดน้ำค้าง" },
  { id: 7, name: "ปุนัพพสุ", category: "เพชฌฆาต", symbol: "คันธนู" },
  { id: 8, name: "ปุษยะ", category: "ราชา", symbol: "ดอกบัว/วัวตัวผู้" },
  { id: 9, name: "อาศเลษา", category: "สมโณ", symbol: "งู" },
  { id: 10, name: "มาฆะ", category: "ทลิทโท", symbol: "วอ/คานหาม" },
  { id: 11, name: "บุรพผลคุนี", category: "มหัทธโณ", symbol: "แคร่" },
  { id: 12, name: "อุตรผลคุนี", category: "โจโร", symbol: "ขาเตียง" },
  { id: 13, name: "หัสตะ", category: "ภูมิปาโล", symbol: "ฝ่ามือ" },
  { id: 14, name: "จิตรา", category: "เทศาตรี", symbol: "แก้วมณี" },
  { id: 15, name: "สวาตี", category: "เทวี", symbol: "ประทีป/ดวงไฟ" },
  { id: 16, name: "วิสาขา", category: "เพชฌฆาต", symbol: "คันชั่ง" },
  { id: 17, name: "อนุราธะ", category: "ราชา", symbol: "ดอกไม้" },
  { id: 18, name: "เชษฐา", category: "สมโณ", symbol: "ตุ้มหู" },
  { id: 19, name: "มูละ", category: "ทลิทโท", symbol: "หางช้าง" },
  { id: 20, name: "ปุรพษาฒ", category: "มหัทธโณ", symbol: "งาช้าง" },
  { id: 21, name: "อุตรษาฒ", category: "โจโร", symbol: "ขวาน" },
  { id: 22, name: "ศรวณะ", category: "ภูมิปาโล", symbol: "หู" },
  { id: 23, name: "ธนิษฐา", category: "เทศาตรี", symbol: "กลอง" },
  { id: 24, name: "ศตภิษัช", category: "เทวี", symbol: "ดอกไม้ 100 ดอก" },
  { id: 25, name: "ปุรพภัทรบท", category: "เพชฌฆาต", symbol: "ขาเตียง" },
  { id: 26, name: "อุตรภัทรบท", category: "ราชา", symbol: "ขาเตียง" },
  { id: 27, name: "เรวดี", category: "สมโณ", symbol: "ปลา" }
];
